services:
  - type: web
    name: applications-shopify
    env: docker
    plan: free
    # Docker runtime uses the Dockerfile for build and start commands
    envVars:
      - key: NODE_ENV
        value: production
      - key: SHOPIFY_API_KEY
        value: 5a9b344563aae1d4c0f19723aaffc9d1
      - key: SHOPIFY_API_SECRET
        sync: false
      - key: SCOPES
        value: write_products
      - key: HOST
        sync: false
      - key: DATABASE_URL
        value: file:./dev.sqlite
