# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a9b344563aae1d4c0f19723aaffc9d1"
name = "applications"
application_url = "https://applications-shopify.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topics = ["products/update"]
path = "/webhooks/products/update"
uri = "https://applications-shopify.onrender.com/webhooks/products/update"

[[webhooks.subscriptions]]
topics = ["products/delete"]
path = "/webhooks/products/delete"
uri = "https://applications-shopify.onrender.com/webhooks/products/delete"

[[webhooks.subscriptions]]
topics = ["products/create"]
path = "/webhooks/products/create"
uri = "https://applications-shopify.onrender.com/webhooks/products/create"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
path = "/webhooks/app/scopes_update"
uri = "https://applications-shopify.onrender.com/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
path = "/webhooks/app/uninstalled"
uri = "https://applications-shopify.onrender.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://applications-shopify.onrender.com/auth/callback" ]
