# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "5a9b344563aae1d4c0f19723aaffc9d1"
name = "applications"
application_url = "https://applications-shopify.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

[[webhooks.subscriptions]]
topic = "products/update"
path = "/webhooks/products/update"

[[webhooks.subscriptions]]
topic = "products/create"
path = "/webhooks/products/create"

[[webhooks.subscriptions]]
topic = "app/scopes_update"
path = "/webhooks/app/scopes_update"

[[webhooks.subscriptions]]
topic = "app/uninstalled"
path = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://applications-shopify.onrender.com/auth/callback" ]
